name: "Notify Slack channel with a text message"
author: rainui28
description: "Post (fancy) message in a Slack channel"
branding:
  color: purple
  icon: message-circle
inputs:
  channel-id:
    description: "Channel ID where the text will be posted"
    required: true
  value:
    description: |
      Mechanism delivery expected value:
      - 'text' -> [Required] message to send in Slack channel. 
      - 'blocks' -> [Required] either raw json payload that complies Slack API blocks 
                    format.
      - 'templates' -> [Required] template filename host on github.com/evryfs/notify-slack-action/templates. 
    required: true
  mechanism:
    description: "Mechanism delivery of the message. Either 'text', 'blocks' or 'templates'"
    required: false
    default: text
runs:
  using: 'node20'
  main: 'index.js'
